import"./modulepreload-polyfill.js";import{r as b,l as Q,j as e,D as U,a as D,c as _,s as B,d as F,R as K}from"./queueDB.js";const E=4,I=({referenceImages:r})=>{var w;if(!((w=r==null?void 0:r.images)!=null&&w.length))return null;const l=r.images,c=r.mode,h=l.slice(0,E),d=l.length-E,p=c==="paired"?"⇌ Pr":"◈ Si",y=c==="paired"?`Paired — ${l.length} image${l.length>1?"s":""}`:`Single — ${l.length} image${l.length>1?"s":""}`,m=l.map(x=>x.name).join(", ");return e.jsxs("div",{className:"flex items-center gap-1 flex-shrink-0",title:`Ref images (${y}): ${m}`,children:[e.jsx("span",{className:`text-[8px] font-bold px-1 py-0.5 rounded leading-none flex-shrink-0 ${c==="paired"?"bg-violet-100 dark:bg-violet-900/30 text-violet-700 dark:text-violet-300":"bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300"}`,children:p}),h.map((x,k)=>e.jsx("div",{className:`w-6 h-6 rounded overflow-hidden flex-shrink-0\r
                        ring-1 ring-slate-300 dark:ring-slate-600\r
                        hover:ring-blue-400 dark:hover:ring-blue-500\r
                        transition-all duration-150 hover:scale-110`,title:x.name,children:e.jsx("img",{src:x.data,alt:x.name,className:"w-full h-full object-cover"})},k)),d>0&&e.jsxs("span",{className:`w-6 h-6 rounded flex-shrink-0 flex items-center justify-center\r
                         text-[8px] font-bold bg-slate-200 dark:bg-slate-700\r
                         text-slate-500 dark:text-slate-400\r
                         ring-1 ring-slate-300 dark:ring-slate-600`,children:["+",d]})]})},X=({task:r,index:l})=>r.status==="processed"?e.jsx("div",{className:`w-7 h-7 rounded-full flex items-center justify-center flex-shrink-0\r
                    bg-gradient-to-br from-emerald-400 to-emerald-600\r
                    shadow-md shadow-emerald-500/30`,children:e.jsx("svg",{className:"w-3.5 h-3.5 text-white",fill:"none",viewBox:"0 0 24 24",stroke:"currentColor",strokeWidth:3,children:e.jsx("path",{strokeLinecap:"round",strokeLinejoin:"round",d:"M5 13l4 4L19 7"})})}):r.status==="error"?e.jsx("div",{className:`w-7 h-7 rounded-full flex items-center justify-center flex-shrink-0\r
                    bg-gradient-to-br from-red-400 to-red-600\r
                    shadow-md shadow-red-500/30`,children:e.jsx("svg",{className:"w-3.5 h-3.5 text-white",fill:"none",viewBox:"0 0 24 24",stroke:"currentColor",strokeWidth:3,children:e.jsx("path",{strokeLinecap:"round",strokeLinejoin:"round",d:"M6 18L18 6M6 6l12 12"})})}):r.status==="current"?e.jsxs("div",{className:"relative w-7 h-7 flex-shrink-0",children:[e.jsx("div",{className:"absolute inset-0 rounded-full animate-spin border-2 border-transparent border-t-blue-500 border-r-blue-500"}),e.jsx("div",{className:"absolute inset-0 flex items-center justify-center text-[10px] font-bold text-blue-600 dark:text-blue-400",children:l+1})]}):e.jsx("div",{className:`w-7 h-7 rounded-full flex items-center justify-center flex-shrink-0\r
                    border-2 bg-white dark:bg-slate-800 text-[10px] font-bold\r
                    border-blue-400 text-blue-600 dark:border-blue-500 dark:text-blue-400`,children:l+1}),$=()=>e.jsxs("span",{className:`inline-flex items-center gap-1 text-[10px] font-bold px-2 py-0.5 rounded-full\r
                   bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300`,children:[e.jsx("svg",{className:"w-2.5 h-2.5",fill:"none",viewBox:"0 0 24 24",stroke:"currentColor",strokeWidth:2.5,children:e.jsx("path",{strokeLinecap:"round",strokeLinejoin:"round",d:"M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"})}),"Image"]}),G=`w-full px-2 py-1.5 text-xs font-medium
  text-slate-700 dark:text-slate-300
  bg-slate-50 dark:bg-slate-700/50
  border border-slate-200 dark:border-slate-600
  hover:border-blue-400 dark:hover:border-blue-500
  rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500/20
  focus:border-blue-500 transition-all`,H=`w-full px-3 py-2.5 text-sm
  border-2 border-slate-200 dark:border-slate-600 rounded-xl
  bg-slate-50 dark:bg-slate-700/60
  text-slate-900 dark:text-white
  placeholder-slate-400 dark:placeholder-slate-500
  focus:outline-none focus:ring-2 focus:ring-blue-500/30 focus:border-blue-500
  transition-all`,j=({label:r,value:l,color:c})=>e.jsxs("div",{className:`flex flex-col items-center justify-center px-4 py-2\r
                  bg-white/60 dark:bg-slate-700/40 rounded-xl border\r
                  border-slate-200/60 dark:border-slate-600/40 min-w-[72px]`,children:[e.jsx("span",{className:`text-lg font-extrabold leading-none ${c}`,children:l}),e.jsx("span",{className:"text-[10px] font-medium text-slate-500 dark:text-slate-400 mt-0.5",children:r})]});function J(){var S,R;const[r,l]=b.useState([]),[c,h]=b.useState(null),[d,p]=b.useState({}),[y,m]=b.useState(!1),[w,x]=b.useState(null);b.useEffect(()=>{const t=a=>{document.documentElement.classList.toggle("dark",a),localStorage.setItem("theme",a?"dark":"light")};chrome.storage.local.get(["darkMode"],a=>{a.darkMode!==void 0?t(a.darkMode):t(localStorage.getItem("theme")!=="light")});const s=(a,n)=>{n==="local"&&"darkMode"in a&&t(a.darkMode.newValue)};return chrome.storage.onChanged.addListener(s),()=>chrome.storage.onChanged.removeListener(s)},[]),b.useEffect(()=>{k();const t=s=>{s.action==="queueUpdated"&&k()};return chrome.runtime.onMessage.addListener(t),()=>chrome.runtime.onMessage.removeListener(t)},[]);const k=async()=>{try{const t=await Q();l(t||[])}catch(t){console.error("❌ [TaskManager]",t)}},W=async t=>{try{await D(t),await k(),chrome.runtime.sendMessage({action:"queueUpdated"})}catch(s){console.error(s)}},z=async()=>{if(confirm("Are you sure you want to clear all tasks?"))try{await _(),l([]),chrome.runtime.sendMessage({action:"queueUpdated"})}catch(t){console.error(t)}},M=async(t,s)=>{try{const a=r.findIndex(q=>q.id===t);if(a===-1)return;const n=[...r],i=n[a],{prompt:o,aspectRatio:g,autoAnimate:f}=s;n[a]={...i,prompt:o!==void 0?o:i.prompt,settings:{...i.settings,...g!==void 0&&{aspectRatio:g},...f!==void 0&&{autoAnimate:f}}},await B(n),l(n),chrome.runtime.sendMessage({action:"queueUpdated"})}catch(a){console.error(a)}},V=t=>{var a,n;const s=r.find(i=>i.id===t);s&&(h(t),p({prompt:s.prompt||"",aspectRatio:((a=s.settings)==null?void 0:a.aspectRatio)||"none",autoAnimate:((n=s.settings)==null?void 0:n.autoAnimate)??!1}),m(!0))},P=async()=>{if(c)try{const t=r.findIndex(g=>g.id===c);if(t===-1)return;const s=[...r],a=s[t],{prompt:n,aspectRatio:i,autoAnimate:o}=d;s[t]={...a,prompt:n,settings:{...a.settings,aspectRatio:i,autoAnimate:o}},await B(s),l(s),m(!1),h(null),chrome.runtime.sendMessage({action:"queueUpdated"})}catch(t){console.error(t)}},u=r.length,N=r.filter(t=>t.status==="processed").length,C=r.filter(t=>t.status==="current").length,T=r.filter(t=>t.status==="pending").length,v=r.filter(t=>t.status==="error").length,A=u>0?Math.round(N/u*100):0,L=r.find(t=>t.id===c);return e.jsxs("div",{className:"relative min-h-screen kling-bg",children:[e.jsx(U,{}),e.jsx("div",{className:`sticky top-0 z-30\r
                      bg-white/80 dark:bg-slate-900/80 backdrop-blur-xl\r
                      border-b border-slate-200/70 dark:border-slate-700/50\r
                      shadow-sm`,children:e.jsxs("div",{className:"max-w-[1400px] mx-auto px-6 py-3 flex items-center gap-5 flex-wrap",children:[e.jsxs("div",{className:"flex items-center gap-3 flex-shrink-0",children:[e.jsx("div",{className:`p-2 bg-gradient-to-br from-blue-500 to-violet-500\r
                            rounded-xl shadow-md shadow-blue-500/25`,children:e.jsx("svg",{className:"h-5 w-5 text-white",fill:"none",viewBox:"0 0 24 24",stroke:"currentColor",strokeWidth:2,children:e.jsx("path",{strokeLinecap:"round",strokeLinejoin:"round",d:"M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"})})}),e.jsxs("div",{children:[e.jsx("h1",{className:"text-base font-bold text-slate-900 dark:text-white leading-none",children:"Task Manager"}),e.jsx("p",{className:"text-[11px] text-slate-500 dark:text-slate-400 mt-0.5",children:"Meta AI Automator"})]})]}),e.jsxs("div",{className:"flex items-center gap-2 flex-wrap",children:[e.jsx(j,{label:"Total",value:u,color:"text-slate-700 dark:text-slate-200"}),e.jsx(j,{label:"Done",value:N,color:"text-emerald-600 dark:text-emerald-400"}),e.jsx(j,{label:"Running",value:C,color:"text-blue-600 dark:text-blue-400"}),e.jsx(j,{label:"Pending",value:T,color:"text-slate-500 dark:text-slate-400"}),v>0&&e.jsx(j,{label:"Errors",value:v,color:"text-red-600 dark:text-red-400"})]}),e.jsxs("div",{className:"flex-1 min-w-[140px] space-y-1",children:[e.jsx("div",{className:"w-full h-1.5 rounded-full bg-slate-200 dark:bg-slate-700 overflow-hidden",children:e.jsx("div",{className:`h-full rounded-full bg-gradient-to-r from-blue-500 to-violet-400\r
                              transition-all duration-700 ease-out`,style:{width:`${A}%`}})}),e.jsxs("div",{className:"flex justify-between items-center",children:[e.jsxs("span",{className:"text-[10px] font-semibold text-slate-500 dark:text-slate-400",children:[A,"% complete"]}),e.jsxs("span",{className:"text-[10px] text-slate-400 dark:text-slate-500",children:[N,"/",u]})]})]}),e.jsxs("button",{onClick:z,disabled:u===0,className:`flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-sm font-semibold\r
                       bg-red-500 hover:bg-red-600 active:bg-red-700 text-white\r
                       shadow-sm shadow-red-500/25\r
                       disabled:opacity-35 disabled:cursor-not-allowed\r
                       hover:scale-[1.03] active:scale-[0.97]\r
                       transition-all duration-200 flex-shrink-0`,children:[e.jsx("svg",{className:"h-3.5 w-3.5",fill:"none",viewBox:"0 0 24 24",stroke:"currentColor",strokeWidth:2,children:e.jsx("path",{strokeLinecap:"round",strokeLinejoin:"round",d:"M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"})}),"Clear All"]})]})}),e.jsxs("div",{className:"relative z-10 max-w-[1400px] mx-auto px-6 py-6",children:[u===0&&e.jsxs("div",{className:`flex flex-col items-center justify-center py-24 gap-4\r
                          bg-white/60 dark:bg-slate-800/50 backdrop-blur-xl\r
                          rounded-2xl border border-slate-200/60 dark:border-slate-700/40\r
                          shadow-lg`,children:[e.jsx("div",{className:`w-16 h-16 rounded-2xl bg-slate-100 dark:bg-slate-700\r
                            flex items-center justify-center shadow-inner`,children:e.jsx("svg",{className:"h-8 w-8 text-slate-350 dark:text-slate-500",fill:"none",viewBox:"0 0 24 24",stroke:"currentColor",strokeWidth:1.5,children:e.jsx("path",{strokeLinecap:"round",strokeLinejoin:"round",d:"M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4"})})}),e.jsxs("div",{className:"text-center",children:[e.jsx("h3",{className:"text-base font-semibold text-slate-900 dark:text-white mb-1",children:"No tasks in queue"}),e.jsx("p",{className:"text-sm text-slate-500 dark:text-slate-400",children:"Add tasks from the sidepanel to get started"})]})]}),u>0&&e.jsxs("div",{className:`bg-white/70 dark:bg-slate-800/60 backdrop-blur-xl\r
                          rounded-2xl border border-slate-200/60 dark:border-slate-700/40\r
                          shadow-lg overflow-hidden`,children:[e.jsx("div",{className:"overflow-x-auto",children:e.jsxs("table",{className:"w-full min-w-[720px] border-collapse table-fixed",children:[e.jsxs("colgroup",{children:[e.jsx("col",{style:{width:"6%"}}),e.jsx("col",{style:{width:"10%"}}),e.jsx("col",{style:{width:"44%"}}),e.jsx("col",{style:{width:"12%"}}),e.jsx("col",{style:{width:"18%"}}),e.jsx("col",{style:{width:"10%"}})]}),e.jsx("thead",{children:e.jsx("tr",{className:`bg-gradient-to-r from-slate-50/80 to-blue-50/40\r
                               dark:from-slate-800/80 dark:to-blue-950/30\r
                               border-b border-slate-200/70 dark:border-slate-700/50`,children:["#","Type","Prompt","Ratio","Preview","Actions"].map((t,s)=>e.jsx("th",{className:`py-2.5 px-3 text-[10px] font-bold uppercase tracking-wider
                                    text-slate-400 dark:text-slate-500
                                    ${s===0||s===5?"text-center":"text-left"}`,children:t},t))})}),e.jsx("tbody",{className:"divide-y divide-slate-100/70 dark:divide-slate-700/40",children:r.map((t,s)=>{var a,n,i;return e.jsxs("tr",{className:`group transition-colors duration-100
                                  hover:bg-blue-50/30 dark:hover:bg-blue-950/15
                                  ${t.status==="current"?"bg-blue-50/40 dark:bg-blue-950/20":t.status==="processed"?"bg-emerald-50/20 dark:bg-emerald-950/10":t.status==="error"?"bg-red-50/20 dark:bg-red-950/10":""}`,children:[e.jsx("td",{className:"py-2.5 px-3 text-center",children:e.jsx("div",{className:"flex justify-center",children:e.jsx(X,{task:t,index:s})})}),e.jsx("td",{className:"py-2.5 px-3",children:e.jsx($,{})}),e.jsx("td",{className:"py-2 px-2 align-top",children:w===t.id?e.jsx("textarea",{autoFocus:!0,value:t.prompt||"",onChange:o=>l(g=>g.map(f=>f.id===t.id?{...f,prompt:o.target.value}:f)),onBlur:o=>{M(t.id,{prompt:o.target.value}),x(null)},onKeyDown:o=>{o.key==="Escape"&&(M(t.id,{prompt:o.target.value}),x(null))},rows:4,className:`w-full px-2.5 py-2 text-sm\r
                            text-slate-800 dark:text-slate-200\r
                            bg-white dark:bg-slate-700/80\r
                            border-2 border-blue-500 dark:border-blue-400\r
                            rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500/25\r
                            resize-none shadow-lg shadow-blue-500/10\r
                            transition-all duration-150 placeholder:text-slate-400`,placeholder:"Task prompt…"}):e.jsx("div",{onClick:()=>x(t.id),className:`w-full px-2.5 py-1.5 text-sm\r
                            text-slate-800 dark:text-slate-200\r
                            bg-transparent border border-transparent rounded-lg\r
                            hover:bg-slate-50 dark:hover:bg-slate-700/40\r
                            hover:border-slate-300 dark:hover:border-slate-600\r
                            cursor-text truncate transition-all duration-150\r
                            min-h-[34px] flex items-center`,title:t.prompt||"Click to edit prompt…",children:t.prompt?e.jsx("span",{className:"truncate block",children:t.prompt}):e.jsx("span",{className:"text-slate-400 dark:text-slate-600 italic",children:"Click to edit…"})})}),e.jsx("td",{className:"py-2 px-2",children:e.jsxs("select",{value:((a=t.settings)==null?void 0:a.aspectRatio)||"none",onChange:o=>M(t.id,{aspectRatio:o.target.value}),className:G,children:[e.jsx("option",{value:"none",children:"—"}),e.jsx("option",{value:"1:1",children:"1:1"}),e.jsx("option",{value:"9:16",children:"9:16"}),e.jsx("option",{value:"16:9",children:"16:9"}),e.jsx("option",{value:"4:3",children:"4:3"}),e.jsx("option",{value:"3:4",children:"3:4"})]})}),e.jsx("td",{className:"py-2.5 px-3",children:((i=(n=t.referenceImages)==null?void 0:n.images)==null?void 0:i.length)>0?e.jsx(I,{referenceImages:t.referenceImages}):e.jsx("div",{className:`w-9 h-9 rounded-xl flex items-center justify-center border\r
                                        bg-blue-50 dark:bg-blue-900/20 border-blue-200 dark:border-blue-800`,children:e.jsx("svg",{className:"w-4 h-4 text-blue-400 dark:text-blue-500",fill:"none",viewBox:"0 0 24 24",stroke:"currentColor",strokeWidth:1.5,children:e.jsx("path",{strokeLinecap:"round",strokeLinejoin:"round",d:"M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"})})})}),e.jsx("td",{className:"py-2.5 px-3",children:e.jsxs("div",{className:"flex items-center justify-center gap-1.5",children:[e.jsx("button",{onClick:()=>V(t.id),className:`h-7 w-7 flex items-center justify-center rounded-lg\r
                                     bg-slate-100 dark:bg-slate-700/50\r
                                     text-slate-400 dark:text-slate-500\r
                                     hover:bg-blue-100 dark:hover:bg-blue-900/30\r
                                     hover:text-blue-600 dark:hover:text-blue-400\r
                                     hover:scale-110 active:scale-95\r
                                     transition-all duration-150`,title:"Edit task",children:e.jsx("svg",{className:"h-3.5 w-3.5",fill:"none",viewBox:"0 0 24 24",stroke:"currentColor",strokeWidth:2,children:e.jsx("path",{strokeLinecap:"round",strokeLinejoin:"round",d:"M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"})})}),e.jsx("button",{onClick:()=>W(t.id),className:`h-7 w-7 flex items-center justify-center rounded-lg\r
                                     bg-slate-100 dark:bg-slate-700/50\r
                                     text-slate-400 dark:text-slate-500\r
                                     hover:bg-red-100 dark:hover:bg-red-900/30\r
                                     hover:text-red-600 dark:hover:text-red-400\r
                                     hover:scale-110 active:scale-95\r
                                     transition-all duration-150`,title:"Delete task",children:e.jsx("svg",{className:"h-3.5 w-3.5",fill:"none",viewBox:"0 0 24 24",stroke:"currentColor",strokeWidth:2,children:e.jsx("path",{strokeLinecap:"round",strokeLinejoin:"round",d:"M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"})})})]})})]},t.id)})})]})}),e.jsxs("div",{className:`px-4 py-2.5 bg-slate-50/60 dark:bg-slate-800/40\r
                            border-t border-slate-200/60 dark:border-slate-700/40\r
                            flex items-center justify-between`,children:[e.jsxs("span",{className:"text-[11px] text-slate-400 dark:text-slate-500",children:[u," ",u===1?"task":"tasks"," total"]}),e.jsxs("span",{className:"text-[11px] text-slate-400 dark:text-slate-500",children:[N," completed · ",T," pending · ",C," running",v>0?` · ${v} error${v>1?"s":""}`:""]})]})]})]}),y&&L&&e.jsx("div",{className:`fixed inset-0 z-50 flex items-center justify-center p-4\r
                        bg-black/40 backdrop-blur-sm`,onClick:t=>{t.target===t.currentTarget&&(m(!1),h(null))},children:e.jsxs("div",{className:`bg-white dark:bg-slate-800 rounded-2xl shadow-2xl\r
                          border border-slate-200/50 dark:border-slate-700/40\r
                          w-full max-w-lg overflow-hidden\r
                          animate-in fade-in zoom-in-95 duration-150`,children:[e.jsxs("div",{className:`flex items-center justify-between px-6 py-4\r
                            border-b border-slate-200/60 dark:border-slate-700/40\r
                            bg-gradient-to-r from-blue-50/50 to-violet-50/30\r
                            dark:from-blue-950/30 dark:to-slate-800/0`,children:[e.jsxs("div",{className:"flex items-center gap-3",children:[e.jsx("div",{className:"p-1.5 bg-gradient-to-br from-blue-500 to-violet-500 rounded-lg shadow-sm",children:e.jsx("svg",{className:"h-4 w-4 text-white",fill:"none",viewBox:"0 0 24 24",stroke:"currentColor",strokeWidth:2,children:e.jsx("path",{strokeLinecap:"round",strokeLinejoin:"round",d:"M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"})})}),e.jsxs("div",{children:[e.jsx("h3",{className:"text-sm font-bold text-slate-900 dark:text-white",children:"Edit Task"}),e.jsx("p",{className:"text-[10px] text-slate-500 dark:text-slate-400",children:e.jsx($,{})})]})]}),e.jsx("button",{onClick:()=>{m(!1),h(null)},className:`h-7 w-7 flex items-center justify-center rounded-lg\r
                           text-slate-400 hover:text-slate-600 dark:text-slate-500 dark:hover:text-slate-300\r
                           hover:bg-slate-100 dark:hover:bg-slate-700 transition-colors`,children:e.jsx("svg",{className:"h-4 w-4",fill:"none",viewBox:"0 0 24 24",stroke:"currentColor",strokeWidth:2,children:e.jsx("path",{strokeLinecap:"round",strokeLinejoin:"round",d:"M6 18L18 6M6 6l12 12"})})})]}),e.jsxs("div",{className:"px-6 py-5 space-y-5",children:[e.jsxs("div",{children:[e.jsx("label",{className:`block text-xs font-semibold text-slate-500 dark:text-slate-400\r
                                   uppercase tracking-wider mb-2`,children:"Prompt"}),e.jsx("textarea",{value:d.prompt,onChange:t=>p({...d,prompt:t.target.value}),rows:4,className:`${H} resize-none`,placeholder:"Enter task prompt…"})]}),e.jsxs("div",{children:[e.jsx("label",{className:`block text-xs font-semibold text-slate-500 dark:text-slate-400\r
                                   uppercase tracking-wider mb-2`,children:"Aspect Ratio"}),e.jsxs("select",{value:d.aspectRatio||"none",onChange:t=>p({...d,aspectRatio:t.target.value}),className:H,children:[e.jsx("option",{value:"none",children:"No Aspect Ratio"}),e.jsx("option",{value:"1:1",children:"1:1 — Square"}),e.jsx("option",{value:"9:16",children:"9:16 — Portrait"}),e.jsx("option",{value:"16:9",children:"16:9 — Landscape"}),e.jsx("option",{value:"4:3",children:"4:3"}),e.jsx("option",{value:"3:4",children:"3:4"})]})]}),e.jsxs("div",{className:"flex items-center justify-between gap-4",children:[e.jsxs("div",{children:[e.jsx("label",{className:`block text-xs font-semibold text-slate-500 dark:text-slate-400\r
                                     uppercase tracking-wider`,children:"Auto Animate"}),e.jsx("p",{className:"text-[10px] text-slate-400 dark:text-slate-500 mt-0.5",children:"Animate each image after generation"})]}),e.jsxs("label",{className:"relative inline-flex items-center cursor-pointer flex-shrink-0",children:[e.jsx("input",{type:"checkbox",className:"sr-only peer",checked:!!d.autoAnimate,onChange:t=>p({...d,autoAnimate:t.target.checked})}),e.jsx("div",{className:`relative w-10 h-5 rounded-full transition-colors duration-200\r
                                  bg-slate-300 dark:bg-slate-600\r
                                  peer-focus:ring-2 peer-focus:ring-violet-300 dark:peer-focus:ring-violet-700\r
                                  after:content-[''] after:absolute after:top-[2px] after:start-[2px]\r
                                  after:bg-white after:rounded-full after:h-4 after:w-4\r
                                  after:transition-all after:shadow-sm\r
                                  peer-checked:after:translate-x-5\r
                                  peer-checked:bg-violet-600`})]})]}),((R=(S=L.referenceImages)==null?void 0:S.images)==null?void 0:R.length)>0&&e.jsxs("div",{className:`rounded-xl border border-teal-200/60 dark:border-teal-800/30\r
                                bg-teal-50/40 dark:bg-teal-900/10 p-3.5`,children:[e.jsx("p",{className:`text-[10px] font-bold text-teal-600 dark:text-teal-400\r
                                 uppercase tracking-wider mb-2.5`,children:"Reference Images — read-only"}),e.jsx(I,{referenceImages:L.referenceImages})]})]}),e.jsxs("div",{className:`flex gap-3 px-6 py-4\r
                            border-t border-slate-200/60 dark:border-slate-700/40\r
                            bg-slate-50/50 dark:bg-slate-800/50`,children:[e.jsx("button",{onClick:()=>{m(!1),h(null)},className:`flex-1 px-4 py-2.5 rounded-xl font-semibold text-sm\r
                           bg-white dark:bg-slate-700 border border-slate-200 dark:border-slate-600\r
                           text-slate-700 dark:text-slate-200\r
                           hover:bg-slate-50 dark:hover:bg-slate-600\r
                           transition-colors`,children:"Cancel"}),e.jsx("button",{onClick:P,className:`flex-1 px-4 py-2.5 rounded-xl font-semibold text-sm\r
                           bg-gradient-to-r from-blue-600 to-violet-600\r
                           hover:from-blue-500 hover:to-violet-500\r
                           text-white shadow-md shadow-blue-500/20\r
                           hover:shadow-lg hover:scale-[1.02] active:scale-[0.98]\r
                           transition-all duration-200`,children:"Save Changes"})]})]})})]})}F.createRoot(document.getElementById("root")).render(e.jsx(K.StrictMode,{children:e.jsx(J,{})}));
